name: gh-pages Deploy

on:
  pull_request:
    types:
      - closed
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - run: |
          echo The PR was merged
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Bulid
        run: |
          yarn
          gulp

      - name: Modify gift of gulp-gh-pages
        run: |
          cd node_modules/gulp-gh-pages/
          npm install --save gift@0.10.2
          cd ../../

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
