name: Publish

on:
  pull_request:
    types:
      - closed
    branches: [ "master" ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
    - run: |
        echo The PR was merged
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Publish
      run: |
        yarn
        gulp
        cd node_modules/gulp-gh-pages/
        npm install --save gift@0.10.2
        cd ../../ 
        gulp deploy
